export const DADOS_EXCEL_BASE = [
    ['STATUS DE LIGACAO', 'VOLUME'],
    ['BAIXA UTILIZACAO', 551],
    ['CENTRAL NAO CADASTRADA', 29],
    ['CLIENTE INDISPONIVEL', 3812],
    ['COMPROU EM OUTRO TELEFONE', 10],
    ['CONTA PENDENTE + DE 30_DIAS', 11],
    ['DISPONIBILIDADE / CSO', 26],
    ['ERRO DE CADASTRO', 119],
    ['FAX', 327],
    ['INSATISFACAO COM A TELEFONICA', 72],
    ['JA FOI CONTATADO', 214],
    ['LIGACOES NAO COMPLETADAS', 263],
    ['MENSAGEM DE OPERADORA (TELEFONIA)', 302],
    ['MUDANCA DE ENDERECO', 30],
    ['NAO ATENDE', 7586],
    ['NAO AUTORIZOU RET DO MULTILINK', 6],
    ['NAO CONCORDA C/ A PERMANENCIA MINIMA', 5],
    ['NAO OBTEVE TODAS AS INFORMACOES DE PROMOCAO', 1],
    ['NAO POSSUI COMPUTADOR', 1107],
    ['NAO POSSUI CONFIGURACAO MINIMA DO PC', 25],
    ['NAO TEM INTERNET', 558],
    ['NECESSIDADE E BENEFICIO EM BANDA LARGA', 45],
    ['OCUPADO', 1203],
    ['OUTRO TIPO DE TECNOLOGIA', 28],
    ['OUTROS MOTIVOS', 106],
    ['PII', 5],
    ['PLANO DE CONSUMO', 5],
    ['POSSUI PRODUTO SIMILAR', 295],
    ['POSSUI SPEEDY', 118],
    ['PRECO', 28],
    ['PREFERE CONCORRENCIA', 30],
    ['PREFERE CONTATAR 0800', 22],
    ['PROBLEMAS FINANCEIROS', 116],
    ['RECUSOU-SE A CONVERSAR', 618],
    ['RESTRICAO TECNICA / CSO', 37],
    ['SECRETARIA ELETRONICA', 3726],
    ['SEGMENTO NAO PERMITIDO', 4],
    ['VAI PENSAR', 118],
    ['VENDA ATENDENTE', 200],
  [],
  ['Tabela de Consulta'],
    [
      'NOME DO OPERADOR',
      'CLIENTE INDISPONIVEL',
      'FAX',
      'NAO ATENDE',
      'OCUPADO',
      'VENDA ATENDENTE',
    ],
    ['ADELAIDE CRISTINA DIAS PEREIRA', 1, null, null, null, null],
    ['ADIEL PASSOS DOS SANTOS', 43, 2, 34, 18, 1],
    ['ADILSON RODOLFO E SILVA', 5, null, 2, null, null],
    ['ADRIANA APARECIDA DE LIMA E SILVA', 11, null, 2, null, null],
    ['ADRIANA DE SOUZA FERNANDES', 24, null, 3, null, 1],
    ['ADRIANA LOPES DE OLIVEIRA', 11, null, 13, 4, null],
    ['ADRIANA SANTOS OLIVEIRA', null, null, null, 7, null],
    ['ADRIELLE VIRGINIA BRAGA', 2, null, 3, null, null],
    ['ALAN HENRIQUE DE JESUS', null, null, 11, 3, null],
    ['ALBERTO CESAR RODRIGUES DO NASCIMENTO', 1, null, 12, null, null],
    ['ALCIONE SOARES DE SOUZA', 28, null, 4, null, 1],
    ['ALESANDRA DA SILVA SANTOS', 19, null, 1, 1, null],
    ['ALESSANDRA DE PAULA RIBEIRO', 1, null, null, 4, null],
    ['ALESSANDRA LUDGERO DE CARVALHO', 3, null, 3, 2, null],
    ['ALESSANDRA MARIA CARVALHO', 7, null, 2, 16, null],
    ['ALESSANDRA PEDROSO LEAL', null, null, 4, null, null],
    ['ALESSANDRA SIRO', null, null, null, 1, null],
    ['ALEXANDRA FERREIRA', null, null, 24, 1, null],
    ['ALEXANDRE CUNHA RAMOS', 8, null, 4, 4, null],
    ['ALEXANDRE ELISEI LEAL', 4, null, 3, 1, null],
    ['ALEXANDRE FERREIRA DIAS DAS SILVA', 4, null, 10, 1, null],
    ['ALINE MACIEL BARROSO', 90, 5, 157, 31, 2],
    ['ALINE MAIRA JUSTINO DOS SANTOS', 2, null, null, null, null],
    ['ALINE MARQUES FELINTO', null, 1, 11, 2, 2],
    ['ALINE MARQUES PRADO', 5, null, 1, null, null],
    ['ALZIRA LEITE CARVALHO', 1, null, null, null, null],
    ['AMADEU', 38, 10, 107, 12, 1],
    ['AMANDA PEREIRA DA SILVA', 3, null, 4, null, null],
    ['ANA ADRIELE RAMOS', 7, 1, 18, 6, 1],
    ['ANA ANGELICA BARBOSA', 1, null, 12, 1, null],
    ['ANA CARLA NASCIMENTO LEITAO', null, 1, 2, null, null],
    ['ANA CLAUDIA PEREIRA DA SILVA', 26, null, 4, 2, 2],
    ['ANA FERNANDA PEREIRA SANTOS', 4, null, 20, 7, null],
    ['ANA LUCIA DORNELES DA SILVA', 1, null, 2, 49, null],
    ['ANA LUCIA SIQUEIRA MACHADO', 40, 5, 66, 20, 2],
    ['ANA MARIA MEDEIROS DE LIMA', null, 1, 116, 6, 1],
    ['ANA PAULA AUGUSTO BRAGA', 1, null, 14, null, 1],
    ['ANA PAULA DA M RAMOS', 1, null, 7, 1, null],
    ['ANA PAULA DE SOUZA', 5, null, 22, 3, null],
    ['ANA PAULA PANICHEK QUINSAN', 5, null, 26, null, null],
    ['ANA PAULA SANTOS PLESKY', null, null, null, 3, null],
    ['ANA PAULA SOUZA DA SILVA', 1, null, 2, null, null],
    ['ANA PAULA VIEIRA DE OLIVEIRA', 1, null, 8, null, null],
    ['ANA TEREZA CORNELIO', null, null, 3, 1, null],
    ['ANDERSON GARCIA DANTAS', 4, 1, 23, 4, null],
    ['ANDRE FELIPE SELGA BRAGA', null, null, 3, null, null],
    ['ANDRE HENRIQUE OLIVEIRA LIMA', 33, 2, 34, 5, 4],
    ['ANDRE LUIS DE OLIVEIRA', 23, null, null, null, 3],
    ['ANDRE LUIZ MOREIRA', 3, 2, 39, 5, null],
    ['ANDRE RICARDO DE SOUZA', 2, null, null, null, null],
    ['ANDREAS NICOLAU KAMINSKI', 1, null, 6, 1, 1],
    ['ANDREIA EVANGELISTA DA SILVA', null, null, 3, null, null],
    ['ANDRESSA RODRIGUES GODOI', 1, null, null, null, null],
    ['ANDREY PALMA NEDER', 1, null, null, null, null],
    ['ANDREZA CARLA DE SIQUEIRA', 1, null, null, null, null],
    ['ANDREZA CRISTINA MACENA DA SILVA', 22, 1, 229, 6, 3],
    ['ANDRIELE ALVES SILVA', 11, null, 50, 1, 1],
    ['ANGELA GONDIM', 3, 1, 6, 3, null],
    ['ANIA PAULA RIBEIRO BATISTA', 1, null, 5, null, null],
    ['ARACELE LEAO SILVERIO MELO', 3, null, null, 3, null],
    ['ARI RENATO DE CASTILHO', 1, null, 1, null, null],
    ['ARIANE APARECIDA MUNFORD', 3, null, null, null, null],
    ['ARNALDO CARDOSO DE BRITO JUNIOR', null, null, 4, 2, null],
    ['AUREA CRISTINA DE JESUS BALLA', null, null, 8, null, 1],
    ['BEATRIZ SILVA SANTOS', 2, null, 6, null, null],
    ['BEATRIZ VELLOZO GOVONI PENHA DE CARVALHO', 5, null, 6, 4, null],
    ['BRENDALY MARCONDES AMANCIO', 7, null, 23, 1, null],
    ['BRUNA BRITO SANTOS', 5, null, 10, 3, 1],
    ['BRUNA GOMES XAVIER', 10, null, 1, 3, null],
    ['BRUNO MARCAL RICOTTA', null, null, 2, null, null],
    ['CARLOS ANTONIO DIAS MILLAN', null, null, 4, null, null],
    ['CARLOS HENRIQUE PESSOA DE CARVALHO', 7, null, 14, 1, null],
    ['CAROL AMELIA DE OLIVEIRA GIFFONI', 1, 1, null, 2, null],
    ['CAROLINA ARIANA REZENDE', null, null, 1, null, null],
    ['CAROLINA BARBOSA DA SILVA', 19, null, 2, null, 2],
    ['CELI MARA DE CAMPOS OLIVEIRA', 18, null, 3, null, null],
    ['CEZAR TIECHER RODRIGUES', 51, 4, 51, 15, 1],
    ['CIDINEIA XAVIER BATISTA', 1, null, 3, 1, null],
    ['CÍNTIA FERREIRA DE OLIVEIRA SILVA ', 64, 6, 170, 15, 8],
    ['CLAUDIA', 142, 26, 398, 37, 3],
    ['CLEIDE OLIVEIRA DE FARIAS', 6, 1, 1, null, null],
    ['CRISTIANE CANDIDO AZEREDO', null, null, 12, 3, null],
    ['CRISTIANE DIAS CASTILHO DE PAULA', 67, 12, 303, 26, 4],
    ['DAILSON DE FREITAS AGUIAR JUNIOR', 2, null, 10, 9, null],
    ['DANIEL GODOI MAIA', null, null, 1, null, null],
    ['DANIELA CALDERARO DE AMORIM', 8, null, 3, 3, null],
    ['DANIELA LOPES DE OLIVEIRA PALHARES', 5, 2, 46, 5, null],
    ['DANIELA RENATA DE OLIVEIRA', null, null, 16, null, null],
    ['DANIELE APARECIDA A ALVARENGA', 13, null, 3, 4, 1],
    ['DANIELLE APARECIDA SIMOES DE LIMA', 6, null, 5, 1, null],
    ['DANIELLE CRISTINA FREIRE', 3, null, null, null, null],
    ['DANIELLE DE PAULA', 2, null, null, null, null],
    ['DANIELLE LUZIA RIBEIRO', 1, null, 5, 3, null],
    ['DANIELLE POLLYANNA DE ALMEIDA', 12, 1, 1, 2, 2],
    ['DAVID LEANDRO SILVA', 118, 15, 201, 17, 7],
    ['DEBORA BARBOSA DA SILVA', 1, null, null, null, null],
    ['DEBORA MARIA SOUZA DE MORAIS', 1, null, null, null, null],
    ['DEBORA PEREIRA MIRANDA', 3, null, 8, 10, null],
    ['DEBORA SANTOS DE PAULA', 2, null, 5, 2, null],
    ['DEBORAH CRISTINA GOMES PAULINO', null, null, 23, 1, null],
    ['DELCIMAR BARROS SILVA', 28, 1, null, null, null],
    ['DIANA LUCIENE SILVA DE MORAIS', 4, null, 7, 6, null],
    ['DIEGO SANTOS ONORIO', 1, null, null, null, null],
    ['DINALVA AIRES DE SALES', 1, null, 1, null, null],
    ['EDGAR PRUDENCIO', 9, 2, 2, null, null],
    ['EDICLEIA CRISTINA FONSECA VELOSO', 2, 1, 14, 1, null],
    ['EDIL FERNANDO PASTOREK', 5, null, null, null, 1],
    ['EDINEIA MARIA DA SILVA', 6, null, 3, null, null],
    ['EDMAR SANTOS', 2, null, null, 1, null],
    ['EDMAR SOARES DOS SANTOS', 1, null, 1, null, null],
    ['EDNA APARECIDA SILVA COTRIM', 1, null, 4, 3, null],
    ['EDUARDO DA SILVA MELO', 6, 1, 10, 2, null],
    ['EDUARDO RAMIS DUGO', 1, null, null, null, null],
    ['ELAINE APARECIDA MOIZES BENTO', 1, null, 10, null, 1],
    ['ELAINE CRISTINA GONCALVES SANTANA', null, null, 4, null, 1],
    ['ELAINE CRISTINA PEREIRA', null, null, 1, 1, null],
    ['ELAINE CRISTINA RISSO NISHIMARU', 32, 10, 407, 12, 5],
    ['ELAINE MARTINS DA SILVA LIMA', 2, null, 26, 4, 1],
    ['ELAINE SOUSA DINIZ', null, null, 2, null, null],
    ['ELEN CAMARGO SILVA', 22, null, 2, null, null],
    ['ELIANE APARECIDA MACHADO', null, null, 1, null, null],
    ['ELIANE APARECIDA SOUZA SILVA', null, null, 7, 1, null],
    ['ELIZABETH ALVES DE CAMPOS', 27, null, 4, 3, 2],
    ['ELIZABETH T F DE SIQUEIRA', 2, null, null, null, null],
    ['ELOIZA CRISTINA DE SENE', null, null, 2, null, null],
    ['ELZENY BICALHO DOS SANTOS', 2, null, 22, null, null],
    ['ENEUDA BEZERRA DE LIMA AVILA', null, null, 1, null, null],
    ['ERICA DORES DA COSTA', 23, 1, 8, 1, 1],
    ['ERICK RAMALHO SARAIVA', null, null, 1, null, null],
    ['ERIKA CORREA DE SOUZA', null, null, null, 47, 1],
    ['ERIQUE DOURADO DE OLIVEIRA', 1, 1, 21, 2, null],
    ['EUNICE HELENA DE SOUZA', 2, null, 5, null, 1],
    ['EVANDRO ALVES DE OLIVEIRA LEMES', 4, 1, 4, 5, null],
    ['EVANILDA ALVES DE OLIVEIRA', 3, null, 14, 3, null],
    ['EVELINE NEVES LEITE', 1, null, 1, null, null],
    ['EVILANIA BEZERRA DE LIMA', null, null, 13, null, 1],
    ['FABIANA RODRIGUES DA SILVA', 3, null, null, 4, null],
    ['FABIANE MARIA SILVA', 1, 2, 14, 3, null],
    ['FABIO IGNACIO NEVES', 9, null, 6, null, 1],
    ['FABRICIO CRUZ MENDES', 16, null, 6, null, 2],
    ['FATIMA APARECIDA ALBUQUERQUE AMANCIO', 34, 1, null, 1, null],
    ['FATIMA MOHAMAD MAZLOUM', 2, null, 22, 8, 3],
    ['FERNANDA CRISTINA DA SILVA', null, 1, null, 6, null],
    ['FERNANDA FONSECA NAVARRO PEREIRA', null, null, 11, null, null],
    ['FERNANDA ORSI DA SILVA', 6, null, 1, 1, null],
    ['FRANCELE RIBEIRO DE OLIVEIRA', 1, null, null, null, null],
    ['FRANCILENE FEITOSA DA SILVA', 3, null, 7, 1, null],
    ['FRANCISCA ISABEL FERREIRA DA SILVA PAZZINI', 2, null, null, null, null],
    ['GABRIEL RAPOSO DE SOUZA', 1, null, 5, null, null],
    ['GABRIELA SANTOS DO NASCIMENTO', 2, null, 8, null, null],
    ['GABRIELLE FONTES SIMONI', 1, null, null, null, null],
    ['GEISIANE KAREN DE OLIVEIRA', 2, null, 2, 2, null],
    ['GISELE DE QUADRO MOREIRA BARROS', 4, 1, 9, null, null],
    ['GISELE MOREIRA DOS SANTOS', 18, null, 17, 13, 1],
    ['GISELE RIBEIRO GUIMARAES', 19, null, null, null, 1],
    ['GISELLE EVANGELISTA DA COSTA', 1, null, 8, null, null],
    ['GISLAINE PEREIRA MACHADO', 1, null, null, 1, null],
    ['GISLENE LOPES DA SILVA', null, null, 18, 1, null],
    ['GLAUCIA BARBOZA VIEIRA', 8, 4, 46, 17, 3],
    ['GLAUCIA FATIMA SILVA LARA', 20, 3, 47, 4, null],
    ['GLEIBER RODRIGO ARAUJO AMORIM', 1, null, null, 1, null],
    ['GRASIELE PEREIRA DE OLIVEIRA', 31, null, 18, 4, 1],
    ['GRAZIELA PALOMARES GOMES DA SILVA', 29, null, 6, null, 1],
    ['GRAZIELE ALMEIDA', 1, null, null, null, null],
    ['GRAZIELE DE PAULA BARBOSA', 37, 2, 42, 2, 2],
    ['HERNANE LELIS MACEDO DA SILVA', 1, null, null, null, null],
    ['ISAAC GERALDO SILVESTRE SILVA', 33, null, 13, 1, null],
    ['IZABEL CRISTINA SANTOS', 7, null, 9, 3, null],
    ['JACQUES EDGAR BARBOSA', 13, null, 2, null, null],
    ['JAIR FERREIRA DE SENA', 2, null, 8, 5, null],
    ['JANAINA BRITO DOS SANTOS', 4, 1, 11, 3, null],
    ['JANAINA NASCIMENTO DA SILVA', null, null, 1, null, null],
    ['JANAINA RIBEIRO', 3, null, 19, 1, null],
    ['JAQUELINE FARIA DA SILVA', 6, null, 13, 1, null],
    ['JAQUELINE TRAJANO DE CASTRO', 2, null, 1, null, null],
    ['JEAN AROLDO SAITO SALUSTIANO', 6, null, null, null, 2],
    ['JEAN RICARDO CAMARGO DE CASTILHO', 3, null, null, null, null],
    ['JOAO', 190, 29, 373, 40, 3],
    ['JOAO PAULO DINIZ', 12, 1, 18, null, 3],
    ['JOAO PAULO MONTEIRO', 2, null, 4, 3, 1],
    ['JOAO PAULO PEREIRA', 2, null, null, null, null],
    ['JONATHAN LIMA SANTOS', 4, null, 2, 2, 1],
    ['JOSE KELLER NASCIMENTO', 3, 1, 6, 1, null],
    ['JOSE MARIO DA ROCHA OLIVEIRA JUNIOR', 4, null, 11, null, null],
    ['JOSE NILTON DE ARAUJO JUNIOR', 72, 8, 94, 17, 1],
    ['JOSE RONALDO XAVIER ALVES', 3, 2, 10, 2, 1],
    ['JULIANA APARECIDA HELBUSTO', 32, null, 4, 1, null],
    ['JULIANA COSTA DE ANDRADE', 2, null, null, null, null],
    ['JULIANA DOS SANTOS', 11, null, 2, 4, null],
    ['JULIANA MENDES PAIVA', 1, null, 12, 1, null],
    ['JULIANA RIBEIRO MOREIRA', 3, null, 8, 1, null],
    ['JULIANO EMANOEL QUEIROZ DOS SANTOS', null, null, 13, 1, null],
    ['KAREN CENIRA MEDEIROS YULE', 1, null, 9, null, null],
    ['KARINA COSTA PEREIRA', 1, null, null, null, null],
    ['KARINA FLORIANO DIAS', 17, null, 1, 1, 2],
    ['KARINE BAYERLEIN VALENTIM', 1, 1, 7, 1, null],
    ['KAROLINE PEREIRA MARTINS', null, null, 3, null, null],
    ['KATIA APARECIDA MOREIRA DA SILVA', null, null, 3, 2, null],
    ['KATIA REGINA MACIEL', 3, null, null, null, null],
    ['KATIA WIVIANE SANTOS DA COSTA', 1, null, 2, 2, null],
    ['LAIDE CRISTINA AZEVEDO DE OLIVEIRA', 4, null, 10, null, null],
    ['LAIR ESTEVES TEIXEIRA', 2, 1, 12, 1, 1],
    ['LAÍS JARDIM PEREIRA', 3, null, null, null, null],
    ['LARISSA LESSA FERREIRA', 2, null, 17, 8, null],
    ['LEANDRO CARDOSO GONCALVES DE SOUZA', 1, null, null, null, null],
    ['LEANDRO FERNANDES VERZANI', null, 1, 1, 49, 1],
    ['LEANDRO LUIZ DA SILVA', 2, 1, 12, null, null],
    ['LEILA DE MORAIS DIAS', 12, null, 22, 1, 1],
    ['LEILA MARCONDES', 6, 1, 17, 5, null],
    ['LEILANE MATEUS DE OLIVEIRA', 17, null, 1, null, 1],
    ['LEONARDO AUGUSTO ALKMIN', 24, null, 1, null, null],
    ['LEONARDO DE ARAUJO DOS SANTOS', null, null, 5, 1, null],
    ['LICIA ALBRES PERMEGIANI GOMES', 3, 1, 12, 2, 1],
    ['LIDIANA PAVAN NELSON', 26, 1, 22, 7, 1],
    ['LIDIANE MAYRA SIGIANI', 1, null, null, null, null],
    ['LIDIANE TOMAZ DE SOUZA GARCIA', null, null, 2, null, null],
    ['LILIAN RIBEIRO DA SILVA CARLINI', null, null, 1, null, null],
    ['LIVIA MARIA CHAVES', 19, null, 23, 7, null],
    ['LUANA EMANUELA ROSA', null, null, 14, 1, 1],
    ['LUANA SABRINA NAVES', 1, null, 5, 1, 2],
    ['LUCAS RAFAEL BORGES DE SOUZA', 2, null, null, null, null],
    ['LUCIA SOUZA PINTO', null, null, 2, null, null],
    ['LUCIANA CAMPBELL F DOS REIS', 6, null, 8, null, null],
    ['LUCIANA FATIMA DE LIMA', 27, null, 2, 1, 2],
    ['LUCILENE DA SILVA ALVES', 21, null, null, 1, null],
    ['LUCILENE FIGUEIREDO', 2, null, 4, 4, null],
    ['LUCILIA FONTES DE SOUZA', 2, null, null, null, null],
    ['MADERLEY CRISTINA CAMARGO', null, null, 1, null, null],
    ['MAIRA SIMAO', 3, null, 14, 3, null],
    ['MARCEL RODRIGO DOS SANTOS', 1, null, null, null, null],
    ['MARCELO DE JESUS PEREIRA', 20, null, null, 4, null],
    ['MARCELO DOUGLAS DE CASTRO', 1, null, null, null, null],
    ['MARCELO RODRIGUES', 32, 5, 53, 8, 2],
    ['MARCIA APARECIDA PACHECO FARIAS', 1, null, 13, 3, null],
    ['MARCIA CRISTINA CARNEIRO', 9, null, 4, null, 1],
    ['MARCIA CRISTINA NOGUEIRA DA SILVA', null, null, 9, null, null],
    ['MARCOS RODOLFO MATEUS DE OLIVEIRA', null, 1, 6, null, null],
    ['MARCOS RODRIGUES DE SOUZA', null, null, 1, null, null],
    ['MARCUS VINICIUS SOUZA DA SILVA', 2, null, 6, null, 1],
    ['MARIA AMELIA COSTA', 13, null, 2, null, null],
    ['MARIA APARECIDA', 31, 7, 91, 10, 1],
    ['MARIA FATIMA COSTA DE SOUZA', 2, 2, 15, 2, null],
    ['MARIANA CAMPBELL FRANCO DOS REIS', 1, 1, 9, 1, null],
    ['MARIANNE DE SOUZA LIMA', null, null, 3, 2, null],
    ['MARILYN DE LIMA', null, null, 1, 1, null],
    ['MARLI DOS SANTOS PEREIRA', null, null, 15, 10, null],
    ['MICHELLY VEDOVATTO GONCALVES', null, null, null, 4, null],
    ['MILENA AUGUSTA CARDOSO', 1, null, null, null, null],
    ['MILENA DE SOUSA NASC DA  SILVA', null, null, 4, null, null],
    ['MILLER DE SIQUEIRA BARCELLOS ', 63, 1, 89, 12, 1],
    ['MIRELA MOURA RASQUINHA', 5, null, 15, null, 1],
    ['MONICA TALITA DA SILVA', 1, null, 14, 2, null],
    ['MONIQUE FABIANE MOREIRA ', 6, null, 4, 2, 1],
    ['NADIMA RAMOS PEREIRA', 16, null, 10, 1, null],
    ['NIKOLAS LOPES STEFANESCU', 15, null, null, null, null],
    ['NILTON SANTOS CORREA JUNIOR', 4, null, 6, 1, null],
    ['NOEMI SOARES DE SOUZA ', 37, 7, 85, 8, 3],
    ['NORMA SUELI SANTOS', 49, null, 5, null, 1],
    ['NUBIA ROSA PEREIRA', 2, null, 6, 1, null],
    ['PAMELLA DA SILVA ALBRECHT', 2, null, 14, 1, null],
    ['PAMYLA SERRA LIMA', 3, null, 15, 12, null],
    ['PAOLA PUGLIEZE', 2, null, 11, 4, null],
    ['PATRICIA APARECIDA DOS SANTOS RIBAS', 2, null, 8, 2, null],
    ['PATRICIA DA SILVA FERREIRA', 18, null, 11, 1, null],
    ['PATRICIA DA SILVA PEREIRA', null, null, 5, null, null],
    ['PATRICIA DE CASSIA VIANA', 22, null, 2, null, null],
    ['PATRICIA LOSNAK', 34, null, 9, null, 2],
    ['PATRICIA LUIZA IRENO', 4, null, null, null, 1],
    ['PAULA CARVALHO DE CAMARGO QUEIROZ', 6, null, 12, null, null],
    ['PAULA SERAGGI', 28, null, 3, 1, 2],
    ['PAULO FRANCIS DA SILVA MARTINS', 1, null, 1, 1, null],
    ['PAULO HENRIQUE JUNIOR', 32, 7, 85, 12, 13],
    ['PAULO HENRIQUE RIBEIRO LOURENCO', 2, null, 2, null, null],
    ['PAULO SERGIO DE ANDRADE', null, null, 16, null, null],
    ['PEDRO', 177, 18, 372, 31, 8],
    ['PEDRO HENRIQUE MACEDO RIBEIRO', 48, 3, 121, 33, 5],
    ['POLIANA RANGEL DE SOUZA GODOI', 1, null, null, null, null],
    ['PRISCILA APARECIDA GAEFKE DE VASCONCELLOS', 1, null, 1, 1, null],
    ['PRISCILA BANHETI DIOGO', 4, 1, 30, 9, null],
    ['PRISCILA SILVA CASTRO', 54, 9, 153, 19, null],
    ['RAFAEL ANTUNES', 3, null, 2, 11, null],
    ['RAFAEL DE CASTILHO PEREIRA LIMA', 12, null, 7, null, 1],
    ['RAFAEL DE OLIVEIRA CRUZ', 11, null, 9, null, 1],
    ['RAFAEL DUARTE DA SILVA', 1, null, 1, 1, null],
    ['RAFAELA DE FATIMA MONTALVAO', 5, null, 16, 2, null],
    ['RAFAELA JOSE DE PAULA', 6, null, 6, 6, null],
    ['RAMAATON CIRIACO CARDOZO', 16, null, 15, 2, null],
    ['RAPHAEL HENRIQUE DUARTE CORREA', 73, 8, 126, 21, 4],
    ['RAQUEL MIRIAN NOGUEIRA PINTO', 42, 7, 96, 14, 1],
    ['RAQUEL PATRICIA DAS NEVES', 2, 3, 69, 4, null],
    ['RAQUEL SILVA LOBO', 8, null, 1, null, null],
    ['REGIANE DOS SANTOS MARTINS MACHADO', 1, null, null, null, null],
    ['REGIANE MARIS SANTIAGO', 13, null, null, 1, 2],
    ['REGIANE SANTOS SILVA', 1, 1, null, null, null],
    ['REGINA LUCIA DE OLIVEIRA', 6, null, 6, null, null],
    ['RENATA FABIANA SANTOS RIBEIRO', null, null, 13, null, null],
    ['RENATA FRANCISCA DE OLIVEIRA', 4, null, 14, null, null],
    ['RENATO DE ARAUJO DOS SANTOS', 1, 2, 31, null, null],
    ['RITA DE CASSIA GONZAGA DA SILVA', 13, null, null, 3, 1],
    ['ROBERTA APARECIDA ANTUNES', null, null, 46, null, null],
    ['ROBERTA SILVEIRA TEIXEIRA', 76, null, 261, 4, 4],
    ['ROBSON NOGUEIRA', 1, null, 8, 1, null],
    ['RODINELE ALEIXO MOREIRA', 8, null, 25, 11, null],
    ['RODOLFO ANTUNES CAVALCANTE DE SOUZA', 4, null, 7, null, null],
    ['ROGERIA LUDGERO DE CARVALHO', 2, null, null, null, null],
    ['ROGERIO FIRMO DE ALMEIDA', 7, null, 7, 10, null],
    ['ROGERIO MARTINS FERREIRA', 2, null, 4, 2, null],
    ['ROMULO HENRIQUE GONCALVES CLARO', 4, 2, 8, 3, 1],
    ['ROSA MARIA NUNES FERREIRA', 111, 13, 290, 29, 4],
    ['ROSANA ALVES', 20, null, 11, null, null],
    ['ROSANGELA APARECIDA A DE SOUZA', null, 3, 28, 9, 1],
    ['ROSE KELLY NASCIMENTO', null, null, 8, null, null],
    ['ROSELENE GABRIELA B MORAIS SANTOS', null, null, 6, 1, null],
    ['ROSELY ALVES', 2, null, null, null, null],
    ['SANDRA CHAVES MATSUMOTO', 2, 2, 14, 1, 1],
    ['SANDRA VALERIO BARROSO', 2, null, null, null, null],
    ['SARA RIBEIRO FERNANDES MAXIMO', null, 1, 4, null, null],
    ['SAVANA ALVES PINHEIRO', 2, null, null, 1, null],
    ['SEVERINA OLIMPIO FERREIRA GOMES', 2, null, null, null, null],
    ['SHEILA ALVES DA SILVA', 1, null, null, null, null],
    ['SILVANA BALDUINO DA SILVA', 2, 1, 9, null, null],
    ['SIMONE APARECIDA DUARTE BISOFFI', 20, null, 4, 3, 1],
    ['SIMONE CRISTINA DA SILVA', 14, null, 8, 2, null],
    ['SIMONE DE CASSIA DE MELLO MORGILLO', 4, null, 1, null, null],
    ['SORAYA DE PAULA ESTEVAM', 1, 1, 20, 15, 1],
    ['SUELEN LETICIA FONSECA', 1, null, 2, null, null],
    ['SUELLEN OLIVEIRA SOUZA', 80, 7, 178, 21, 5],
    ['SUSAN FRANZ DE OLIVEIRA', 12, 4, 61, 3, 1],
    ['SUZANA MARIA DE MIRANDA', 18, 5, 81, 7, 1],
    ['SUZE INES MARTINS FREIRE', null, null, 1, null, null],
    ['TAIS HERMESDORFF RODRIGUES', 3, null, 3, null, null],
    ['TALITA ALMEIDA CHIARADIA', 1, null, null, 1, null],
    ['TATIANA ANTAO FERREIRA', 2, null, 8, 2, null],
    ['TATIANE APARECIDA DE PAULA', 19, null, 19, null, null],
    ['THAIS PRISCILA BRUN DE OLIVEIRA ', 76, 13, 281, 20, 5],
    ['THATIENE DA SILVA DE OLIVEIRA', 23, null, 1, null, 1],
    ['THIAGO EDUARDO ALMEIDA', 13, 3, 39, 2, null],
    ['THIAGO MOURA DOS SANTOS', 2, null, 10, null, null],
    ['THIAGO WANDER GERALDO', null, null, 13, 1, null],
    ['VALDINEIA APARECIDA TAVARES', 1, null, null, 4, 1],
    ['VALERIA DE SOUZA RENO', 2, null, 1, null, null],
    ['VANESSA DE ALMEIDA LIMA', 1, 1, 6, null, null],
    ['VANIA ELISABETE GOMES', 52, 5, 67, 27, 6],
    ['VANIA GOMES DE ALMEIDA', 25, null, 6, 2, 1],
    ['VERONICA BAZLER', 1, null, 4, null, null],
    ['VICTOR LEONARDO DE LIMA AVILA', null, 1, 13, 3, null],
    ['VIVIAN MACHADO RODRIGUES', null, null, null, 1, null],
    ['VIVIANE APARECIDA ANTUNES I GONCALVES', null, null, 1, null, null],
    ['VIVIANE APARECIDA DA SILVA', 27, null, 6, null, null],
    ['VIVIANE BARRETO DE SOUZA', 22, null, 20, 2, 1],
    ['WILLIAN DA SILVA VIRGILIO', 1, null, 3, null, null],
    ['WILSILENE GONCALVES DE OLIVEIRA', null, null, 1, null, null],
];
