window.RUNTIME_CONFIG = {
  ...(window.RUNTIME_CONFIG || {}),
  API_BASE_URL: '',
  PUBLIC_CANDIDATE_BASE_URL: '',
  PROCESS_DOSSIER_AI_ENDPOINT: '',
  APP_ENV: 'dev',
  APP_VERSION: '0.1.0',
};

window.__RH_API_BASE__ = window.RUNTIME_CONFIG.API_BASE_URL || '';
window.__RH_PUBLIC_CANDIDATE_BASE_URL__ =
  window.RUNTIME_CONFIG.PUBLIC_CANDIDATE_BASE_URL || '';
window.__RH_PROCESS_DOSSIER_AI_ENDPOINT__ =
  window.RUNTIME_CONFIG.PROCESS_DOSSIER_AI_ENDPOINT || '';
