window.RUNTIME_CONFIG = {
  ...(window.RUNTIME_CONFIG || {}),
  API_BASE_URL: 'http://192.168.5.19:8010',
  PUBLIC_CANDIDATE_BASE_URL: '',
};

window.__RH_API_BASE__ = window.RUNTIME_CONFIG.API_BASE_URL;
window.__RH_PUBLIC_CANDIDATE_BASE_URL__ =
  window.RUNTIME_CONFIG.PUBLIC_CANDIDATE_BASE_URL;
