window.RUNTIME_CONFIG = {
  ...(window.RUNTIME_CONFIG || {}),
  API_BASE_URL: 'http://127.0.0.1:8010',
  PUBLIC_CANDIDATE_BASE_URL: '',
};

window.__RH_API_BASE__ = window.RUNTIME_CONFIG.API_BASE_URL;
window.__RH_PUBLIC_CANDIDATE_BASE_URL__ =
  window.RUNTIME_CONFIG.PUBLIC_CANDIDATE_BASE_URL;