stateDiagram-v2
    [*] --> Analise
    Analise --> Qualificado: CV aprovado/decisão RH
    Analise --> NaoQualificado: CV fraco
    Qualificado --> Agendado: entrevista marcada
    Agendado --> Confirmado
    Agendado --> Reagendado
    Confirmado --> Compareceu
    Confirmado --> Faltou
    Reagendado --> Confirmado
    Compareceu --> Aprovado
    Compareceu --> Eliminado
    Compareceu --> BancoTalentos
    NaoQualificado --> BancoTalentos: decisão RH
    NaoQualificado --> Eliminado
    Faltou --> Eliminado
    Aprovado --> [*]
    Eliminado --> [*]
    BancoTalentos --> [*]
